--- 
- hosts: all
  sudo: yes
  tasks:
    - copy:
        src: /etc/ansible/files/Dockerfile
        dest: /tmp/Dockerfile
    - copy:
        src: /etc/ansible/files/local.py
        dest: /tmp/local.py
        decrypt: yes
    - copy:
        src: /etc/ansible/files/default.py
        dest: /tmp/default.py
        decrypt: yes
    - copy:
        src: /etc/ansible/files/django.sql
        dest: /tmp/django.sql
        decrypt: yes
    - copy:
        src: /etc/ansible/files/postgres.pw
        dest: /tmp/postgres.pw
        decrypt: yes
    - shell: sed -i "s/db_host_ip/`hostname --ip-address`/" /tmp/local.py 
    - shell: apt-get update && apt-get install  apt-transport-https ca-certificates curl gnupg-agent software-properties-common && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt-get update && apt-get install docker-ce docker-ce-cli containerd.io
    - shell: mkdir -p /var/lib/postgres/ && docker run --name postgresdb -v /var/lib/postgres:/var/lib/postgresql/data --env-file=/tmp/postgres.pw -d -p 5432:5432 postgres:9.6.0
    - shell: PGPASSWORD=`cat /tmp/postgres.pw|cut -f 2 --delimiter="="` psql -h 127.0.0.1 -p 5432 -U postgres -a -f /tmp/django.sql
    - shell: cd /tmp && docker build --no-cache  --tag django:latest .
    - shell: rm /tmp/*.py django.sql postgres.pw Dockerfile; docker run --name django -d -p 80:80 django:latest;docker restart django
    
